### ISSUE TITLE
عدم همخوانی نسخه موجود در github و docker

### ISSUE THREAD

**Issue by SMMH1999** [redpilllabs/Rainb0w#4]
به دلیل وجود مشکل در ساختار کد و عدم اصلاح هنگام نصب و ساخت کاربر جدید برنامه با خطا مواجه می شود.

برای برطرف کردن این مورد نسخه 3.2 را از github دانلود و با نسخه دانلود شده از سمت docker جایگزین کنید. سپس اقدام به نصب نمائید

**Comment by kyochikuto** [comment]
لطفا متن کامل خطا رو به همراه نوع سیستم عامل درج کنید.

**Comment by SMMH1999** [comment]
![Screenshot 2023-11-07 054309](https://github.com/redpilllabs/Rainb0w/assets/58251087/f2a9ace0-40fc-4356-8bf9-f72927d08553)
اولین تغییر نسبت به نسخه اصلی در این قسمت قابل مشاهده است که با فایل نسخه 3.2 متفاوت است.

![Screenshot 2023-11-07 054620](https://github.com/redpilllabs/Rainb0w/assets/58251087/a5c08dcf-200e-47b6-a289-44236ed9ba7e)
در این مرحله پس از وارد کرد نام با خطای زیر مواجه می شوید.

![Screenshot 2023-11-07 054732](https://github.com/redpilllabs/Rainb0w/assets/58251087/dbbb063f-9ca7-4079-afe4-a30429f5eef6)

### OS: 

> Ubuntu 22.04

### Error: 

> Traceback (most recent call last):
>   File "/root/Rainb0w/lib/configurator.py", line 273, in <module>
>     main()
>   File "/root/Rainb0w/lib/configurator.py", line 254, in main
>     configure()
>   File "/root/Rainb0w/lib/configurator.py", line 227, in configure
>     apply_config(username=username)
>   File "/root/Rainb0w/lib/configurator.py", line 96, in apply_config
>     caddy_insert_params(rainb0w_config, CADDY_CONFIG_FILE)
>   File "/root/Rainb0w/lib/proxy/caddy.py", line 51, in caddy_insert_params
>     if is_domain(rainb0w_config["DOMAINS"]["MAIN_DOMAIN"]):
> NameError: name 'is_domain' is not defined. Did you mean: 'domain'?
> Python configurator did not finish successfully!

**Comment by SMMH1999** [comment]
برای رفع خطا من از گیت [نسخه قبل](https://github.com/redpilllabs/Rainb0w/archive/refs/tags/v3.2.zip) رو دانلود و بعد جایگزین نسخه clone شده کردم.

اسکریپت به صورت کامل اجرا و راه اندازی شد.

**Comment by kyochikuto** [comment]
اصلاحیه اعمال شد لطفا مجددا اخرین نسخه را pull و امتحان کنید. با تشکر از گزارش شما.

**Comment by SMMH1999** [comment]
مشکل پس از تغییرات.

پس از تغییر فایل 
> caddy.py

بخش اول برنامه کدهای مربوط به import مشکل دارد باید به کد های زیر تغییر پیدا کند.

```
from utils.domain_utils import (
    extract_domain, 
    is_domain, 
    is_subdomain
    )
```

**Comment by kyochikuto** [comment]
اصلاح شد. با تشکر.
