### ISSUE TITLE
Your version of Ubuntu is not supported! Only 20.04 and 22.04 versions are supported.

### ISSUE THREAD

**Issue by lolminerxmrig** [redpilllabs/Rainb0w#5]
Hi.
My Ubuntu 23.04

Your version of Ubuntu is not supported! Only 20.04 and 22.04 versions are supported.

![image](https://github.com/redpilllabs/Rainb0w/assets/108659226/f0406f21-f3d0-4e71-ac9c-60d7fd6c224f)

**Comment by kyochikuto** [comment]
Only LTS versions of Ubuntu are supported, you have to rebuild your server with 22.04.
