### ISSUE TITLE
Path for Trojan WebSocket is missing 

### ISSUE THREAD

**Issue by alidxdydz** [redpilllabs/Rainb0w#9]
سلام و خسته نباشید.

من امروز بعد مدتها رنگین کمان رو دوباره نصب کردم و hysteria2 و تمامی پراکسی های ws و grpc کار میکنن بجز trojan ws.
فکر میکنم مربوط به path باشه. چون بر خلاف بقیه خالیه.

همچنین برام سواله که naive کار میکنه یا نه؟ چون با هر کلاینت، سیستم و isp چک کردم، کانکت نشد.

ممنون از زحماتتون

**Comment by kyochikuto** [comment]
دستور زیر چه خروجی داره؟

```
cat ~/Rainb0w_Home/xray/etc/xray.json | grep TROJAN_WS
```

> همچنین برام سواله که naive کار میکنه یا نه؟


برای من هم کار نکرد احتمالا در برخی سرویس دهنده ها کار نمی‌کنه.

**Comment by alidxdydz** [comment]
سلام.
دستورو زدم و path برا trojan ws رو پیدا کردم و الان کار میکنه.
ولی داخل اون فایل txt نهایی که همه کانفیگا داخلشن، path نداره.

**Comment by kyochikuto** [comment]
> ولی داخل اون فایل txt نهایی که همه کانفیگا داخلشن، path نداره.

بله حق با شماست الان برطرف کردم با تشکر از اطلاع رسانی شما.

**Comment by kyochikuto** [comment]
> اگه naive پشت cloudflare میره، اصولا نباید کار کنه، هرچند کند؟ اخیرا هم متوجه شدم یه [کلاینت جدید](https://github.com/Chilledheart/yass) داخل صفحه گیتهاب naive معرفی شده که فقط با naive کار میکنه ولی همین کانفیگ کار نکرد. برا همین برا سوال شد که واقعا سمت سرور درست کار میکنه؟

کلا پروکسی های مبتنی بر HTTP نباید پشت CDN کار کنند اما در این مورد خاص شاید مشکل از ترکیب Naive با Caddy باشه که متاسفانه تغییرش خیلی بنیادین خواهد بود و به صرفه نیست.

**Comment by alidxdydz** [comment]
دو تا سوال هم در مورد sing-box داشتم. میخواستم ببینم شما هم به چنین موردی برخوردین یا نه.

اولی در مورد alpn و ترنسپورت grpc هست. صرفنظر از پروتکل، داخل کلاینت v2rayng، ترنسپورت grpc با [http/1.1,h2] کار میکنه (حتی تکی) ولی کلاینت nekoray فقط با h2 کار میکنه. اضافه کردن http/1.1 باعث از کار افتادن پراکسی میشه.

دومی در مورد dns هسته sing-box بود. وقتی ما وبسایتی رو از طریق پراکسی sing-box باز میکنیم، dns هم از طریق پراکسی ریزالو میشه یا دایرکت؟ چون من هر چقدر به این تصویر نگاه میکنم، فکر میکنم dns هسته sing-box به صورت موازی با پراکسیه و در طولش نیست و برا اینکه dns از پراکسی رد بشه، باید detour مربوط به dns رو به پراکسی تغییر داد.
https://sing-box.sagernet.org/manual/proxy/client/#virtual-interface

**Comment by kyochikuto** [comment]
> ترنسپورت grpc با [http/1.1,h2] کار میکنه (حتی تکی) ولی کلاینت nekobox فقط با h2 کار میکنه. 

فیلترینگ هر ترافیکی که مشابه ترافیک های رایج و مجاز نباشه تشخیص میده برای gRPC هم چون بر پایه ی HTTP2 ساخته شده نیاز به h2 هستش اینکه کلاینت ها چه پیاده سازی دارن رو اطلاع ندارم اما شما تا جای ممکن مشابه ترافیک مجاز تنظیم کنید.

> فکر میکنم dns هسته sing-box به صورت موازی با پراکسیه و در طولش نیست و برا اینکه dns از پراکسی رد بشه، باید detour مربوط به dns رو به پراکسی تغییر داد.

طبق مستندات پروژه اگر خروجی تعیین نشه خروجی پیشفرض انتخاب خواهد شد و در جایی اشاره کرده که خروجی پیشفرض همان اولین مورد در فهرست outbounds هستش البته امتحان نکردم شخصا.
